<?php

function op_registry(): array
{
  return [
    /*  'noop_copy' => [
      'title' => 'noop_copy (тест)',
      'description' => 'Тестовая операция: копирует входной XML в result.xml и пишет report/meta.',
      'handler_file' => __DIR__ . '/operations/noop_copy.php',
      'handler_func' => 'op_noop_copy',
      'redirect_to_report' => true,
      'params' => [
        'note' => [
          'type' => 'string',
          'title' => 'Комментарий (note)',
          'default' => '',
          'required' => false,
          'max_len' => 200,
        ],
      ],
    ],
    */

    /*
    'gpt_ping' => [
      'title' => 'gpt_ping (OpenAI тест)',
      'description' => 'Тест запроса к OpenAI. Пишет результат в gpt_ping.txt.',
      'handler_file' => __DIR__ . '/operations/gpt_ping.php',
      'handler_func' => 'op_gpt_ping',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
      ],
    ],
*/
    /*
    'sleep_test' => [
      'title' => 'Sleep test (progress)',
      'handler_file' => __DIR__ . '/operations/sleep_test.php',
      'handler_func' => 'op_sleep_test',
      'redirect_to_report' => false,
      'params' => [
        ['name'=>'seconds', 'type'=>'int', 'default'=>90, 'min'=>5, 'max'=>600, 'label'=>'Seconds'],
        ['name'=>'tick', 'type'=>'int', 'default'=>2, 'min'=>1, 'max'=>10, 'label'=>'Tick (sec)'],
      ],
    ],
*/
    'sanitize_description_links' => [
      'title' => 'sanitize_description_links (очистить описания: ссылки/телефоны + картинки)',
      'description' => 'Ищет в описании ссылки на изображения, переносит их в список фотографий и удаляет из текста внешние ссылки, телефоны и призывы связаться.',
      'handler_file' => __DIR__ . '/operations/sanitize_description_links.php',
      'handler_func' => 'op_sanitize_description_links',
      'supplier_products_db_handler' => 'supplier_products_db_op_sanitize_description_links',
      'redirect_to_report' => false,
      'params' => [
        'inplace' => [
          'type' => 'string',
          'title' => 'Изменять текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество обрабатываемых товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],



    'analyze_category_products' => [
      'title' => 'analyze_category_products (анализ товаров для категорий)',
      'description' => 'Сканирует датасет, группирует товары по <ozon_category> и <wb_category>, для каждой категории вызывает GPT и заполняет meta_json: description/typical_goods/features/cover_design/video_cover_design. Для Ozon и WB также обновляет метаданные характеристик категории из API. Для Ozon дополнительно сохраняет ключевые поисковые запросы категории из аналитики товаров.',
      'handler_file' => __DIR__ . '/operations/analyze_category_products.php',
      'handler_func' => 'op_analyze_category_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_analyze_category_products',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_categories' => [
          'type' => 'string',
          'title' => 'Максимум категорий (0 = все)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'max_products_per_category' => [
          'type' => 'string',
          'title' => 'Товаров в выборке на категорию',
          'default' => '60',
          'required' => false,
          'max_len' => 10,
        ],
        'max_desc_len' => [
          'type' => 'string',
          'title' => 'Длина description_snippet (0 = не передавать)',
          'default' => '280',
          'required' => false,
          'max_len' => 10,
        ],
        'only_missing' => [
          'type' => 'string',
          'title' => 'Заполнять только пустые блоки (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'refresh_filled_if_changed' => [
          'type' => 'string',
          'title' => 'Обновлять заполненные блоки, если изменились товары (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'search_queries_enabled' => [
          'type' => 'string',
          'title' => 'Собирать поисковые запросы Ozon (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'search_queries_days' => [
          'type' => 'string',
          'title' => 'Период запросов Ozon, дней',
          'default' => '28',
          'required' => false,
          'max_len' => 10,
        ],
        'search_queries_sku_limit' => [
          'type' => 'string',
          'title' => 'Максимум SKU для запросов на категорию',
          'default' => '300',
          'required' => false,
          'max_len' => 10,
        ],
        'search_queries_limit_by_sku' => [
          'type' => 'string',
          'title' => 'Максимум запросов на SKU',
          'default' => '10',
          'required' => false,
          'max_len' => 10,
        ],


      ],
    ],

    'gpt_assign_marketplace_categories' => [
      'title' => 'gpt_assign_marketplace_categories (назначить категории Ozon/WB)',
      'description' => 'Группирует товары по категории поставщика, локально подбирает короткий список кандидатов Ozon/WB из taxonomy и через GPT выбирает наиболее точные категории. Автоматически записывает только уверенные совпадения.',
      'handler_file' => __DIR__ . '/operations/noop_copy.php',
      'handler_func' => 'op_noop_copy',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_assign_marketplace_categories',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'max_groups' => [
          'type' => 'string',
          'title' => 'Ограничить количество категорий поставщика (0 = все)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'max_products_per_group' => [
          'type' => 'string',
          'title' => 'Товаров в выборке на категорию поставщика',
          'default' => '48',
          'required' => false,
          'max_len' => 10,
        ],
        'max_candidates_per_marketplace' => [
          'type' => 'string',
          'title' => 'Кандидатов категорий на маркетплейс',
          'default' => '70',
          'required' => false,
          'max_len' => 10,
        ],
        'llm_candidates_per_marketplace' => [
          'type' => 'string',
          'title' => 'Кандидатов в GPT-запросе на маркетплейс',
          'default' => '42',
          'required' => false,
          'max_len' => 10,
        ],
        'llm_candidate_details_top' => [
          'type' => 'string',
          'title' => 'Сколько топ-кандидатов отправлять с описаниями',
          'default' => '22',
          'required' => false,
          'max_len' => 10,
        ],
        'llm_products_per_group' => [
          'type' => 'string',
          'title' => 'Товаров в GPT-примере на категорию поставщика',
          'default' => '16',
          'required' => false,
          'max_len' => 10,
        ],
        'auto_confidence' => [
          'type' => 'string',
          'title' => 'Порог автозаписи',
          'default' => '0.88',
          'required' => false,
          'max_len' => 10,
        ],
        'product_fallback' => [
          'type' => 'string',
          'title' => 'Fallback по отдельным товарам для смешанных групп (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'fallback_confidence' => [
          'type' => 'string',
          'title' => 'Порог автозаписи fallback',
          'default' => '0.80',
          'required' => false,
          'max_len' => 10,
        ],
        'max_product_fallback_per_group' => [
          'type' => 'string',
          'title' => 'Макс. товаров в fallback на категорию поставщика',
          'default' => '120',
          'required' => false,
          'max_len' => 10,
        ],
        'fallback_chunk_size' => [
          'type' => 'string',
          'title' => 'Товаров в одном fallback GPT-запросе',
          'default' => '12',
          'required' => false,
          'max_len' => 10,
        ],
        'role_prepass' => [
          'type' => 'string',
          'title' => 'Предварительно определять товарную роль группы (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'verify_decisions' => [
          'type' => 'string',
          'title' => 'Проверять выбранные категории вторым GPT-запросом (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'verification_confidence' => [
          'type' => 'string',
          'title' => 'Минимальная уверенность проверки',
          'default' => '0.82',
          'required' => false,
          'max_len' => 10,
        ],
        'apply' => [
          'type' => 'string',
          'title' => 'Записывать уверенные категории (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Заменять уже назначенные категории (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'gpt_fix_title_ru' => [
      'title' => 'gpt_fix_title_ru (добавить рус. тип в название)',
      'description' => 'Если название без кириллицы, GPT добавляет русский тип товара как префикс.',
      'handler_file' => __DIR__ . '/operations/gpt_fix_title_ru.php',
      'handler_func' => 'op_gpt_fix_title_ru',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество исправлений (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Автоматически создать новый dataset (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'gpt_optimize_title_marketplace' => [
      'title' => 'gpt_optimize_title_marketplace (улучшить названия)',
      'description' => 'GPT оптимизирует названия товаров под маркетплейс: нейтрально, понятно и без запрещённых формулировок.',
      'handler_file' => __DIR__ . '/operations/gpt_optimize_title_marketplace.php',
      'handler_func' => 'op_gpt_optimize_title_marketplace',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество обрабатываемых товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Автоматически создать новый dataset (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'gpt_rewrite_title_marketplace' => [
      'title' => 'gpt_rewrite_title_marketplace (улучшить названия)',
      'description' => 'GPT улучшает названия товаров для маркетплейса с учетом описания, категорий и характеристик.',
      'handler_file' => __DIR__ . '/operations/gpt_rewrite_title_marketplace.php',
      'handler_func' => 'op_gpt_rewrite_title_marketplace',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_title',
      'supplier_products_db_args' => ['rewrite'],
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество обрабатываемых товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Автоматически создать новый dataset (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],


    'taxonomy_import_ozon' => [
      'title' => 'taxonomy_import_ozon (импорт категорий Ozon)',
      'description' => 'Импорт категорий Ozon из файла (формат: path > path (A_B)). Прогресс по строкам.',
      'handler_file' => __DIR__ . '/operations/taxonomy_import_ozon.php',
      'handler_func' => 'op_taxonomy_import_ozon',
      'redirect_to_report' => false,
      'params' => [
        'file_path' => [
          'type' => 'string',
          'title' => 'Путь к файлу категорий на сервере',
          'default' => '',
          'required' => false,
          'max_len' => 500,
        ],
        'replace' => [
          'type' => 'string',
          'title' => 'Очистить старые категории перед импортом (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'taxonomy_import_ozon_api' => [
      'title' => 'taxonomy_import_ozon_api (импорт категорий Ozon из API)',
      'description' => 'Запрашивает дерево /v1/description-category/tree, генерирует categories_ozon.txt и импортирует в БД. Прогресс в worker.',
      'handler_file' => __DIR__ . '/operations/taxonomy_import_ozon_api.php',
      'handler_func' => 'op_taxonomy_import_ozon_api',
      'redirect_to_report' => false,
      'params' => [
        'replace' => [
          'type' => 'string',
          'title' => 'Очистить старые категории перед импортом (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'taxonomy_import_wb_api' => [
      'title' => 'taxonomy_import_wb_api (импорт категорий Wildberries из API)',
      'description' => 'Загружает parent categories и subjects из Wildberries Content API и сохраняет их в taxonomy.',
      'handler_file' => __DIR__ . '/operations/taxonomy_import_wb_api.php',
      'handler_func' => 'op_taxonomy_import_wb_api',
      'redirect_to_report' => false,
      'params' => [
        'replace' => [
          'type' => 'string',
          'title' => 'Очистить старые категории перед импортом (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'set_ozon_category' => [
      'title' => 'set_ozon_category (назначить ozon_category)',
      'description' => 'Записывает или заменяет категорию Ozon у выбранных товаров или у всех, если выбор пуст.',
      'handler_file' => __DIR__ . '/operations/set_ozon_category.php',
      'handler_func' => 'op_set_ozon_category',
      'redirect_to_report' => false,
      'params' => [
        'ozon_category' => [
          'type' => 'string',
          'title' => 'Ozon category (например 123_456)',
          'default' => '',
          'required' => false,
          'max_len' => 200,
        ],
        'clear_category' => [
          'type' => 'string',
          'title' => 'Очистить назначенную категорию (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Изменять текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],



    'pixlab_remove_photo_watermarks' => [
      'title' => 'pixlab_remove_photo_watermarks (удалить водяные знаки с фото)',
      'description' => 'Отправляет фотографии товаров в PixLab TXT-REMOVE API, сохраняет очищенные изображения в локальное хранилище и заменяет ссылки на фото у товаров. Использовать только для фотографий, на которые есть права.',
      'handler_file' => __DIR__ . '/operations/pixlab_remove_photo_watermarks.php',
      'handler_func' => 'op_pixlab_remove_photo_watermarks',
      'supplier_products_db_handler' => 'supplier_products_db_op_pixlab_remove_photo_watermarks',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'photos_limit' => [
          'type' => 'string',
          'title' => 'Фото на товар (0 = все)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'remove_white_bg_watermarks' => [
      'title' => 'remove_white_bg_watermarks (локально убрать водяные знаки с белого фона)',
      'description' => 'Без GPT и внешних API очищает только белый фон, связанный с краями изображения, по профилю поставщика. Товар, маркировки и наклейки не трогает, даже если на них остается водяной знак. Заменяет обработанные фото у товаров.',
      'handler_file' => __DIR__ . '/operations/remove_white_bg_watermarks.php',
      'handler_func' => 'op_remove_white_bg_watermarks',
      'supplier_products_db_handler' => 'supplier_products_db_op_remove_white_bg_watermarks',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'photos_limit' => [
          'type' => 'string',
          'title' => 'Фото на товар (0 = все)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать уже очищенные фото (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'protect_radius' => [
          'type' => 'string',
          'title' => 'Защитный радиус вокруг товара (0 = авто)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'luma_min' => [
          'type' => 'string',
          'title' => 'Минимальная яркость фона для очистки',
          'default' => '198',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],



    'gpt_fill_color_vision' => [
      'title' => 'gpt_fill_color_vision (заполнить Цвет по фото)',
      'description' => 'Ищет товары без заполненной характеристики Цвет, определяет до 3 доминирующих цветов по первой картинке через GPT (vision) и записывает результат в текущий датасет.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_color_vision.php',
      'handler_func' => 'op_gpt_fill_color_vision',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_fill_color_vision',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (должна поддерживать vision)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset (1/0) (обычно 0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'set_wb_category' => [
      'title' => 'set_wb_category (назначить wb_category)',
      'description' => 'Записывает или заменяет категорию Wildberries у выбранных товаров или у всех, если выбор пуст.',
      'handler_file' => __DIR__ . '/operations/set_wb_subject.php',
      'handler_func' => 'op_set_wb_category',
      'redirect_to_report' => false,
      'params' => [
        'wb_category' => [
          'type' => 'string',
          'title' => 'WB category (например 1234)',
          'default' => '',
          'required' => false,
          'max_len' => 50,
        ],
        'clear_category' => [
          'type' => 'string',
          'title' => 'Очистить назначенную категорию (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 50,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset автоматически (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'set_wb_subject' => [
      'title' => 'set_wb_subject (legacy alias)',
      'description' => 'Старый алиас для set_wb_category.',
      'handler_file' => __DIR__ . '/operations/set_wb_subject.php',
      'handler_func' => 'op_set_wb_subject',
      'redirect_to_report' => false,
      'params' => [
        'wb_subject_id' => [
          'type' => 'string',
          'title' => 'WB subject id (legacy alias)',
          'default' => '',
          'required' => false,
          'max_len' => 50,
        ],
        'clear_category' => [
          'type' => 'string',
          'title' => 'Очистить назначенную категорию (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 50,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset автоматически (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'gpt_fill_offer_params' => [
      'title' => 'gpt_fill_offer_params (заполнить характеристики товаров по категории)',
      'description' => 'Для товаров с заполненной ozon_category и/или wb_category подтягивает мета соответствующих категорий и через ОДИН GPT-запрос заполняет marketplace-специфичные характеристики. Значения для Ozon пишет в <param>, для Wildberries — в <wb_param>. По умолчанию inplace.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_offer_params.php',
      'handler_func' => 'op_gpt_fill_offer_params',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_fill_offer_params',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'gpt_fill_offer_params_wb' => [
      'title' => 'gpt_fill_offer_params_wb (legacy alias)',
      'description' => 'Старый алиас. Использует ту же объединённую логику, что и gpt_fill_offer_params, и отдельный запуск больше не нужен.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_offer_params.php',
      'handler_func' => 'op_gpt_fill_offer_params',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'detect_brand_from_title' => [
      'title' => 'detect_brand_from_title (определить бренд по названию)',
      'description' => 'Без GPT ищет бренд в названии товара, сверяет кандидатов со справочниками брендов Ozon/WB и заполняет поле brand только если бренд пустой или overwrite=1. Учитывает контекст совместимости, чтобы не записывать Apple/DJI/etc из фраз вроде «для Apple iPhone».',
      'handler_file' => __DIR__ . '/operations/noop_copy.php',
      'handler_func' => 'op_noop_copy',
      'supplier_products_db_handler' => 'supplier_products_db_op_detect_brand_from_title',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать уже заполненный бренд (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'min_score' => [
          'type' => 'string',
          'title' => 'Минимальная уверенность правила',
          'default' => '70',
          'required' => false,
          'max_len' => 5,
        ],
        'brand_list' => [
          'type' => 'string',
          'title' => 'Список брендов поставщика',
          'default' => '',
          'required' => false,
          'max_len' => 20000,
        ],
      ],
    ],

    'analyze_brand_category_map' => [
      'title' => 'analyze_brand_category_map (аудит брендов и категорий)',
      'description' => 'Без GPT строит полную карту бренд-категория по товарам поставщика и сверяет ее со справочниками брендов Ozon/WB: что уже в порядке, где нужно создать бренд, исправить написание, обновить справочник или добавить бренд к категории.',
      'handler_file' => __DIR__ . '/operations/supplier_brand_dictionary.php',
      'handler_func' => 'op_supplier_brand_dictionary_only_for_supplier_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_analyze_brand_category_map',
      'redirect_to_report' => false,
      'params' => [
        'marketplaces' => [
          'type' => 'string',
          'title' => 'Маркетплейсы: all / ozon / wb',
          'default' => 'all',
          'required' => false,
          'max_len' => 50,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'include_ok' => [
          'type' => 'string',
          'title' => 'Показывать в HTML группы без проблем (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 1,
        ],
        'min_similarity' => [
          'type' => 'string',
          'title' => 'Порог похожего написания бренда',
          'default' => '86',
          'required' => false,
          'max_len' => 3,
        ],
      ],
    ],

    'gpt_generate_brand_logo' => [
      'title' => 'gpt_generate_brand_logo (сгенерировать логотип бренда)',
      'description' => 'Через GPT Image генерирует логотип бренда для создания бренда на маркетплейсе и сохраняет готовые файлы под требования Ozon и Wildberries.',
      'handler_file' => __DIR__ . '/operations/supplier_brand_dictionary.php',
      'handler_func' => 'op_supplier_brand_dictionary_only_for_supplier_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_generate_brand_logo',
      'redirect_to_report' => false,
      'params' => [
        'brand' => [
          'type' => 'string',
          'title' => 'Название бренда',
          'default' => '',
          'required' => true,
          'max_len' => 120,
        ],
        'marketplaces' => [
          'type' => 'string',
          'title' => 'Маркетплейсы',
          'default' => 'all',
          'required' => false,
          'max_len' => 32,
        ],
        'source_op_id' => [
          'type' => 'string',
          'title' => 'ID операции аудита брендов',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'image_model' => [
          'type' => 'string',
          'title' => 'GPT Image model',
          'default' => 'gpt-image-2',
          'required' => false,
          'max_len' => 80,
          'options' => ['gpt-image-1-mini', 'gpt-image-1.5', 'gpt-image-2'],
        ],
        'image_quality' => [
          'type' => 'string',
          'title' => 'Качество изображения',
          'default' => 'medium',
          'required' => false,
          'max_len' => 20,
          'options' => ['low', 'medium', 'high'],
        ],
        'image_size' => [
          'type' => 'string',
          'title' => 'Размер генерации GPT',
          'default' => '1024x1024',
          'required' => false,
          'max_len' => 20,
        ],
        'timeout_sec' => [
          'type' => 'string',
          'title' => 'Таймаут OpenAI image_generation, сек',
          'default' => '180',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],

    'gpt_fill_tnved_codes' => [
      'title' => 'gpt_fill_tnved_codes (заполнить коды ТН ВЭД)',
      'description' => 'Строит короткий список допустимых конечных кодов для сочетания категории поставщика и категории Ozon/WB, исключая варианты с обязательной маркировкой, затем выбирает один наиболее общий подходящий код для каждой однородной группы товаров. Для Ozon записывает только точное немаркируемое значение из словаря категории. Индивидуальные GPT-запросы выполняются только для неоднородных групп и исключений.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_tnved_codes.php',
      'handler_func' => 'op_gpt_fill_tnved_codes',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_fill_tnved_codes',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => 'gpt-5.4-mini',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать уже заполненные коды ТН ВЭД (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'min_confidence' => [
          'type' => 'string',
          'title' => 'Минимальная уверенность GPT для записи',
          'default' => '0.82',
          'required' => false,
          'max_len' => 5,
        ],
        'allowed_values_limit' => [
          'type' => 'string',
          'title' => 'Кандидатов на товар до построения общего списка категории',
          'default' => '32',
          'required' => false,
          'max_len' => 5,
        ],
        'category_shortlist_limit' => [
          'type' => 'string',
          'title' => 'Короткий список кодов категории (8-30)',
          'default' => '16',
          'required' => false,
          'max_len' => 5,
        ],
        'category_group_plan' => [
          'type' => 'string',
          'title' => 'Подбирать общий код один раз для однородной группы (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'category_representative_limit' => [
          'type' => 'string',
          'title' => 'Сколько примеров товара проверять в группе',
          'default' => '12',
          'required' => false,
          'max_len' => 5,
        ],
        'analysis_prepass' => [
          'type' => 'string',
          'title' => 'Предварительно разбирать товарную роль для ТН ВЭД (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'verify_decisions' => [
          'type' => 'string',
          'title' => 'Проверять выбранный код вторым GPT-запросом (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'force_decision' => [
          'type' => 'string',
          'title' => 'Всегда выбирать лучший код, даже если нужна проверка человеком (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'force_low_confidence' => [
          'type' => 'string',
          'title' => 'Делать повторный запрос при низкой уверенности (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'verification_confidence' => [
          'type' => 'string',
          'title' => 'Минимальная уверенность проверки',
          'default' => '0.82',
          'required' => false,
          'max_len' => 10,
        ],
        'signature_reuse' => [
          'type' => 'string',
          'title' => 'Переиспользовать решение для похожих товаров (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'group_reuse' => [
          'type' => 'string',
          'title' => 'Переиспользовать устойчивый код внутри группы товаров без GPT (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'memory_auto_fill' => [
          'type' => 'string',
          'title' => 'Переиспользовать код по очень похожим товарам без GPT (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'memory_category_auto_fill' => [
          'type' => 'string',
          'title' => 'Автозаполнять по общей памяти категории поставщика без GPT (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'memory_min_count' => [
          'type' => 'string',
          'title' => 'Минимум совпадений в памяти категории',
          'default' => '3',
          'required' => false,
          'max_len' => 5,
        ],
        'memory_min_share' => [
          'type' => 'string',
          'title' => 'Минимальная доля кода в памяти категории',
          'default' => '0.85',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],



    'gpt_fill_hashtags' => [
      'title' => 'gpt_fill_hashtags (заполнить hashtags по товару и категории)',
      'description' => 'Для товаров с заполненной категорией подтягивает метаданные категории и через GPT генерирует хештеги. Не затирает существующие хештеги, если overwrite=0.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_hashtags.php',
      'handler_func' => 'op_gpt_fill_hashtags',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_fill_hashtags',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать существующий <hashtags> (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'gpt_fill_features' => [
      'title' => 'gpt_fill_features (сгенерировать фишки товара)',
      'description' => 'Для товаров поставщика передает в GPT данные товара и категории, выбирает до 3 главных фишек для будущих плашек на изображении и сохраняет их в поля Фишка 1-3. Не затирает заполненные фишки, если overwrite=0.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_features.php',
      'handler_func' => 'op_gpt_fill_features',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_fill_features',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => 'gpt-5.4-mini',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать существующие фишки (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'gpt_generate_cover_image' => [
      'title' => 'gpt_generate_cover_image (создать обложку товара с инфографикой)',
      'description' => 'Для товаров поставщика передает в отдельную GPT Image модель данные товара, стиль обложки категории, бренд, фишки, комплект и первое фото, создает готовую продающую обложку со всеми текстами, ставит ее первым изображением и сохраняет исходное главное фото дополнительным.',
      'handler_file' => __DIR__ . '/operations/gpt_generate_cover_image.php',
      'handler_func' => 'op_gpt_generate_cover_image',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_generate_cover_image',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'image_size' => [
          'type' => 'string',
          'title' => 'Размер генерации GPT (1200x1600 = Ozon 3:4)',
          'default' => '1200x1600',
          'required' => false,
          'max_len' => 20,
        ],
        'image_quality' => [
          'type' => 'string',
          'title' => 'Качество изображения',
          'default' => 'low',
          'options' => ['low', 'medium', 'high'],
          'required' => false,
          'max_len' => 20,
        ],
        'image_model' => [
          'type' => 'string',
          'title' => 'GPT Image model',
          'default' => 'gpt-image-2',
          'options' => ['gpt-image-1-mini', 'gpt-image-1.5', 'gpt-image-2'],
          'required' => false,
          'max_len' => 80,
        ],
        'input_fidelity' => [
          'type' => 'string',
          'title' => 'Точность сохранения исходного фото (auto/low/high; mini без параметра)',
          'default' => 'auto',
          'required' => false,
          'max_len' => 10,
        ],
        'timeout_sec' => [
          'type' => 'string',
          'title' => 'Таймаут OpenAI image_generation, сек',
          'default' => '180',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать уже созданные GPT-обложки (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'gpt_generate_product_photo_variant' => [
      'title' => 'gpt_generate_product_photo_variant (создать дополнительное фото товара)',
      'description' => 'Для товаров поставщика берет первое обычное фото товара, пропуская GPT-обложку, и через GPT Image создает одно новое реалистичное дополнительное фото этого же товара без инфографики и текста. Новая картинка добавляется в конец списка фото.',
      'handler_file' => __DIR__ . '/operations/gpt_generate_product_photo_variant.php',
      'handler_func' => 'op_gpt_generate_product_photo_variant',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_generate_product_photo_variant',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'only_single_source_photo' => [
          'type' => 'string',
          'title' => 'Только товары с одним обычным фото (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'image_size' => [
          'type' => 'string',
          'title' => 'Размер генерации GPT (1200x1600 = Ozon 3:4)',
          'default' => '1200x1600',
          'required' => false,
          'max_len' => 20,
        ],
        'image_quality' => [
          'type' => 'string',
          'title' => 'Качество изображения',
          'default' => 'low',
          'options' => ['low', 'medium', 'high'],
          'required' => false,
          'max_len' => 20,
        ],
        'image_model' => [
          'type' => 'string',
          'title' => 'GPT Image model',
          'default' => 'gpt-image-2',
          'options' => ['gpt-image-1-mini', 'gpt-image-1.5', 'gpt-image-2'],
          'required' => false,
          'max_len' => 80,
        ],
        'input_fidelity' => [
          'type' => 'string',
          'title' => 'Точность сохранения исходного фото (auto/low/high; mini без параметра)',
          'default' => 'auto',
          'required' => false,
          'max_len' => 10,
        ],
        'timeout_sec' => [
          'type' => 'string',
          'title' => 'Таймаут OpenAI image_generation, сек',
          'default' => '180',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'gpt_generate_video_cover' => [
      'title' => 'gpt_generate_video_cover (создать видео-обложку через Sora)',
      'description' => 'Для товаров поставщика передает в OpenAI Videos API/Sora фото-обложку как визуальный референс, данные товара, фишки, фото товара и video_cover_design категории, генерирует MP4 видео-обложку и записывает ссылку в поле Ozon "Озон.Видеообложка: ссылка". Обычное поле видео не заполняется.',
      'handler_file' => __DIR__ . '/operations/gpt_generate_video_cover.php',
      'handler_func' => 'op_gpt_generate_video_cover',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_generate_video_cover',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'video_model' => [
          'type' => 'string',
          'title' => 'OpenAI video model',
          'default' => 'sora-2',
          'options' => ['sora-2', 'sora-2-2025-12-08', 'sora-2-2025-10-06', 'sora-2-pro', 'sora-2-pro-2025-10-06'],
          'required' => false,
          'max_len' => 80,
        ],
        'video_size' => [
          'type' => 'string',
          'title' => 'Размер Sora video (sora-2: 720x1280; pro: до 1080x1920)',
          'default' => '720x1280',
          'required' => false,
          'max_len' => 20,
        ],
        'video_seconds' => [
          'type' => 'string',
          'title' => 'Длительность Sora-видео, сек (4/8/12/16/20)',
          'default' => '8',
          'required' => false,
          'max_len' => 5,
        ],
        'video_duration_mode' => [
          'type' => 'string',
          'title' => 'Режим длительности',
          'default' => 'full',
          'options' => ['full', 'slow_4_to_8'],
          'required' => false,
          'max_len' => 30,
        ],
        'final_video_size' => [
          'type' => 'string',
          'title' => 'Финальный размер MP4 после Sora (3:4 для Ozon)',
          'default' => '1080x1440',
          'required' => false,
          'max_len' => 20,
        ],
        'final_video_fps' => [
          'type' => 'string',
          'title' => 'Финальный FPS MP4',
          'default' => '25',
          'required' => false,
          'max_len' => 5,
        ],
        'final_video_crf' => [
          'type' => 'string',
          'title' => 'Финальный CRF H.264',
          'default' => '23',
          'required' => false,
          'max_len' => 5,
        ],
        'final_video_maxrate_kbps' => [
          'type' => 'string',
          'title' => 'Ограничение битрейта MP4, kbit/s',
          'default' => '3200',
          'required' => false,
          'max_len' => 10,
        ],
        'source_photos' => [
          'type' => 'string',
          'title' => 'Сколько фото товара учитывать в контексте (1-4)',
          'default' => '3',
          'required' => false,
          'max_len' => 5,
        ],
        'poll_interval_sec' => [
          'type' => 'string',
          'title' => 'Интервал проверки готовности Sora, сек',
          'default' => '10',
          'required' => false,
          'max_len' => 5,
        ],
        'poll_timeout_sec' => [
          'type' => 'string',
          'title' => 'Максимальное ожидание одного видео, сек',
          'default' => '900',
          'required' => false,
          'max_len' => 10,
        ],
        'timeout_sec' => [
          'type' => 'string',
          'title' => 'HTTP-таймаут OpenAI Videos API, сек',
          'default' => '180',
          'required' => false,
          'max_len' => 10,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Заменять уже созданную видео-обложку (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'create_photo_collage' => [
      'title' => 'create_photo_collage (собрать коллаж из 2-3 фото)',
      'description' => 'Для товаров поставщика без GPT берет первые 2-3 обычные фотографии, пропуская GPT-обложки и старые коллажи, собирает аккуратный вертикальный коллаж 1200x1600 и добавляет его в конец списка фото.',
      'handler_file' => __DIR__ . '/operations/create_photo_collage.php',
      'handler_func' => 'op_create_photo_collage',
      'supplier_products_db_handler' => 'supplier_products_db_op_create_photo_collage',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Заменять уже созданный коллаж (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'create_product_specs_photo' => [
      'title' => 'create_product_specs_photo (характеристики на шаблоне категории)',
      'description' => 'Для товаров поставщика без GPT берет фон-шаблон дополнительного фото из данных категории, аккуратно пишет бренд и полезные технические характеристики товара, затем добавляет готовую картинку в конец списка фото.',
      'handler_file' => __DIR__ . '/operations/create_product_specs_photo.php',
      'handler_func' => 'op_create_product_specs_photo',
      'supplier_products_db_handler' => 'supplier_products_db_op_create_product_specs_photo',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'max_chars' => [
          'type' => 'string',
          'title' => 'Максимум характеристик на фото',
          'default' => '8',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Заменять уже созданное фото-характеристики (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'create_video_cover' => [
      'title' => 'create_video_cover (простая видео-обложка без GPT)',
      'description' => 'Для товаров поставщика без GPT берет первые 3-4 фото карточки, исключая фото-характеристики и коллажи, собирает короткую MP4 видео-обложку со стабильным товаром, мягкой динамикой фона и плавной сменой кадров, затем записывает ссылку в поле Ozon "Озон.Видеообложка: ссылка".',
      'handler_file' => __DIR__ . '/operations/create_video_cover.php',
      'handler_func' => 'op_create_video_cover',
      'supplier_products_db_handler' => 'supplier_products_db_op_create_video_cover',
      'redirect_to_report' => false,
      'params' => [
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'source_photos' => [
          'type' => 'string',
          'title' => 'Сколько фото брать в видео (1-4)',
          'default' => '4',
          'required' => false,
          'max_len' => 5,
        ],
        'seconds_per_photo' => [
          'type' => 'string',
          'title' => 'Длительность одного фото, сек',
          'default' => '2.0',
          'required' => false,
          'max_len' => 10,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Заменять уже созданную видео-обложку (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],
    'gpt_fill_same_model' => [
      'title' => 'gpt_fill_same_model (Модель товара)',
      'description' => 'Заполняет рабочую модель товара (тег same_model) для отображения рядом с названием, группировки и экспорта. Сначала берет явные модельные характеристики, затем при необходимости извлекает модель через GPT. Не затирает существующее значение, если overwrite=0.',
      'handler_file' => __DIR__ . '/operations/gpt_fill_same_model.php',
      'handler_func' => 'op_gpt_fill_same_model',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_fill_same_model',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Переписать текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Перезаписывать существующую модель товара (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'min_group_size' => [
          'type' => 'string',
          'title' => 'Минимальный размер группы (1 = заполнять одиночные товары, 2 = только вариации)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'similarity_threshold' => [
          'type' => 'string',
          'title' => 'Порог схожести ключей (0.70–0.99)',
          'default' => '0.90',
          'required' => false,
          'max_len' => 5,
        ],
        'min_confidence' => [
          'type' => 'string',
          'title' => 'Минимальная уверенность GPT для записи (0.50–1.00)',
          'default' => '0.76',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'gpt_generate_description_ru' => [
      'title' => 'gpt_generate_description_ru (умная операция description)',
      'description' => 'Единая операция описаний: для пустых, коротких или слабых описаний пишет нормальный текст; для длинных существующих описаний делает рерайт, сохраняя структуру и органично добавляя ключевые запросы категории.',
      'handler_file' => __DIR__ . '/operations/gpt_generate_description_ru.php',
      'handler_func' => 'op_gpt_generate_description_ru',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_generate_description',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество обрабатываемых товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'min_desc_len' => [
          'type' => 'string',
          'title' => 'Порог: короче N = написать заново, N и длиннее = рерайт',
          'default' => '250',
          'required' => false,
          'max_len' => 10,
        ],
        'rewrite_existing' => [
          'type' => 'string',
          'title' => 'Переписывать существующие длинные description (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'overwrite' => [
          'type' => 'string',
          'title' => 'Legacy: принудительно трогать существующие description (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'use_keywords' => [
          'type' => 'string',
          'title' => 'Использовать keywords из категории (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Изменять текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'gpt_rewrite_description_ru' => [
      'title' => 'gpt_rewrite_description_ru (legacy alias: description)',
      'description' => 'Совместимый алиас на единую операцию описаний: короткие описания дописываются, длинные переписываются с сохранением структуры и ключевыми запросами категории.',
      'handler_file' => __DIR__ . '/operations/noop_copy.php',
      'handler_func' => 'op_noop_copy',
      'supplier_products_db_handler' => 'supplier_products_db_op_gpt_rewrite_description',
      'redirect_to_report' => false,
      'params' => [
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество обрабатываемых товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'min_desc_len' => [
          'type' => 'string',
          'title' => 'Переписывать только description длиной >= N',
          'default' => '120',
          'required' => false,
          'max_len' => 10,
        ],
        'use_keywords' => [
          'type' => 'string',
          'title' => 'Использовать keywords из категории (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'normalize_param_values' => [
      'title' => 'normalize_param_values (нормализовать значения характеристик по таблице соответствий)',
      'description' => 'Заменяет значения характеристик Ozon/WB по таблице feedtools_param_value_map (attr_name/old_value/new_value). Полезно, когда GPT пишет значения, не подходящие для маркетплейсов (например «поливинилхлорид» → «пластик»).',
      'handler_file' => __DIR__ . '/operations/normalize_param_values.php',
      'handler_func' => 'op_normalize_param_values',
      'supplier_products_db_handler' => 'supplier_products_db_op_normalize_param_values',
      'redirect_to_report' => false,
      'params' => [
        'inplace' => [
          'type' => 'string',
          'title' => 'Изменять текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'auto_dataset' => [
          'type' => 'string',
          'title' => 'Создать новый dataset (1/0) (актуально только если inplace=0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'Ограничить количество обрабатываемых товаров (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],

    'update_stock_from_feed' => [
      'title' => 'update_stock_from_feed (обновить <stock> из нового фида)',
      'description' => 'Берёт <stock> из загруженного XML и обновляет/добавляет <stock> в текущем датасете по offer id.',
      'handler_file' => __DIR__ . '/operations/update_stock_from_feed.php',
      'handler_func' => 'op_update_stock_from_feed',
      'redirect_to_report' => false,
      'params' => [
        // сюда run_op_stock_upload.php запишет путь к загруженному файлу
        'feed_path' => [
          'type' => 'string',
          'title' => 'feed_path (internal)',
          'default' => '',
          'required' => true,
          'max_len' => 1000,
        ],
        'inplace' => [
          'type' => 'string',
          'title' => 'Изменять текущий датасет (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'supplier_import_catalog' => [
      'title' => 'supplier_import_catalog (импорт товаров поставщика)',
      'description' => 'Фоновый импорт товаров поставщика из фида, файла или личного кабинета маркетплейса с прогрессом.',
      'handler_file' => __DIR__ . '/operations/supplier_import_catalog.php',
      'handler_func' => 'op_supplier_import_catalog',
      'supplier_products_db_handler' => 'supplier_products_db_op_import_catalog',
      'redirect_to_report' => false,
      'params' => [
        'import_action' => [
          'type' => 'string',
          'title' => 'Действие импорта',
          'default' => 'import',
          'required' => true,
          'max_len' => 40,
        ],
        'source' => [
          'type' => 'string',
          'title' => 'Источник',
          'default' => 'supplier_feed',
          'required' => true,
          'max_len' => 40,
        ],
        'feed_url' => [
          'type' => 'string',
          'title' => 'Ссылка на фид',
          'default' => '',
          'required' => false,
          'max_len' => 1000,
        ],
        'stored_file' => [
          'type' => 'string',
          'title' => 'Токен загруженного файла',
          'default' => '',
          'required' => false,
          'max_len' => 255,
        ],
        'stored_file_name' => [
          'type' => 'string',
          'title' => 'Имя загруженного файла',
          'default' => '',
          'required' => false,
          'max_len' => 255,
        ],
        'ozon_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Ozon',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'wb_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения WB',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
      ],
    ],

    'supplier_push_ozon_content' => [
      'title' => 'supplier_push_ozon_content (отправить товары поставщика в Ozon API)',
      'description' => 'Отправляет выбранные поля DB-товаров поставщика в выбранный кабинет Ozon.',
      'service_key' => 'marketplace_data',
      'dataset_lock' => false,
      'handler_file' => __DIR__ . '/operations/supplier_push_marketplace_content.php',
      'handler_func' => 'op_supplier_push_marketplace_content',
      'supplier_products_db_handler' => 'supplier_products_db_op_push_marketplace_content',
      'supplier_products_db_args' => ['ozon'],
      'redirect_to_report' => false,
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Ozon',
          'default' => '0',
          'required' => true,
          'max_len' => 20,
        ],
        'fields_json' => [
          'type' => 'string',
          'title' => 'JSON массива полей для отправки',
          'default' => '[]',
          'required' => true,
          'max_len' => 2000,
        ],
      ],
    ],

    'ozon_duplicate_pairs_scan' => [
      'title' => 'ozon_duplicate_pairs_scan (собрать дубли товаров Ozon)',
      'description' => 'Ищет товары с ошибкой Ozon "дубль товара", вытаскивает артикул прошедшего модерацию дубля и обновляет таблицу пар для разбора.',
      'handler_file' => __DIR__ . '/operations/ozon_duplicate_pairs_scan.php',
      'handler_func' => 'op_ozon_duplicate_pairs_scan',
      'supplier_products_db_handler' => 'supplier_products_db_op_ozon_duplicate_pairs_scan',
      'redirect_to_report' => false,
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Ozon',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
      ],
    ],

    'supplier_push_wb_content' => [
      'title' => 'supplier_push_wb_content (отправить товары поставщика в WB API)',
      'description' => 'Отправляет выбранные поля DB-товаров поставщика в выбранный кабинет Wildberries.',
      'service_key' => 'marketplace_data',
      'dataset_lock' => false,
      'handler_file' => __DIR__ . '/operations/supplier_push_marketplace_content.php',
      'handler_func' => 'op_supplier_push_marketplace_content',
      'supplier_products_db_handler' => 'supplier_products_db_op_push_marketplace_content',
      'supplier_products_db_args' => ['wb'],
      'redirect_to_report' => false,
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения WB',
          'default' => '0',
          'required' => true,
          'max_len' => 20,
        ],
        'fields_json' => [
          'type' => 'string',
          'title' => 'JSON массива полей для отправки',
          'default' => '[]',
          'required' => true,
          'max_len' => 2000,
        ],
      ],
    ],

    'supplier_sync_ozon_brands_full' => [
      'title' => 'supplier_sync_ozon_brands_full (полная синхронизация брендов Ozon)',
      'description' => 'Обновляет локальный справочник брендов Ozon по категориям второго уровня.',
      'handler_file' => __DIR__ . '/operations/supplier_brand_dictionary.php',
      'handler_func' => 'op_supplier_brand_dictionary_only_for_supplier_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_sync_ozon_brands_full',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'marketplace_data',
      'params' => [
        'ozon_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Ozon',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'refresh_days' => [
          'type' => 'string',
          'title' => 'Считать справочник категории свежим N дней',
          'default' => '30',
          'required' => false,
          'max_len' => 5,
        ],
        'force_refresh' => [
          'type' => 'string',
          'title' => 'Принудительно обновить все категории',
          'default' => '0',
          'required' => false,
          'max_len' => 1,
        ],
        'max_scopes' => [
          'type' => 'string',
          'title' => 'Лимит категорий за запуск (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],

    'supplier_sync_ozon_brands_category' => [
      'title' => 'supplier_sync_ozon_brands_category (обновить бренды выбранных категорий Ozon)',
      'description' => 'Обновляет локальный справочник брендов для категорий второго уровня Ozon, соответствующих выбранным категориям.',
      'handler_file' => __DIR__ . '/operations/supplier_brand_dictionary.php',
      'handler_func' => 'op_supplier_brand_dictionary_only_for_supplier_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_sync_ozon_brands_category',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'marketplace_data',
      'params' => [
        'ozon_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Ozon',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'category_value' => [
          'type' => 'string',
          'title' => 'Код категории Ozon',
          'default' => '',
          'required' => false,
          'max_len' => 191,
        ],
        'category_values_json' => [
          'type' => 'string',
          'title' => 'JSON списка выбранных категорий Ozon',
          'default' => '[]',
          'required' => false,
          'max_len' => 50000,
        ],
        'refresh_days' => [
          'type' => 'string',
          'title' => 'Считать справочник категории свежим N дней',
          'default' => '30',
          'required' => false,
          'max_len' => 5,
        ],
        'force_refresh' => [
          'type' => 'string',
          'title' => 'Принудительно обновить категорию',
          'default' => '1',
          'required' => false,
          'max_len' => 1,
        ],
      ],
    ],

    'supplier_sync_wb_brands_full' => [
      'title' => 'supplier_sync_wb_brands_full (полная синхронизация брендов WB)',
      'description' => 'Проходит по всем subject-категориям Wildberries и обновляет локальный справочник доступных брендов.',
      'handler_file' => __DIR__ . '/operations/supplier_brand_dictionary.php',
      'handler_func' => 'op_supplier_brand_dictionary_only_for_supplier_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_sync_wb_brands_full',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'marketplace_data',
      'params' => [
        'wb_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения WB',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'refresh_days' => [
          'type' => 'string',
          'title' => 'Считать справочник категории свежим N дней',
          'default' => '30',
          'required' => false,
          'max_len' => 5,
        ],
        'force_refresh' => [
          'type' => 'string',
          'title' => 'Принудительно обновить все категории',
          'default' => '0',
          'required' => false,
          'max_len' => 1,
        ],
        'max_scopes' => [
          'type' => 'string',
          'title' => 'Лимит категорий за запуск (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
      ],
    ],

    'supplier_sync_wb_brands_category' => [
      'title' => 'supplier_sync_wb_brands_category (обновить бренды выбранной категории WB)',
      'description' => 'Обновляет локальный справочник брендов для одной или нескольких выбранных категорий Wildberries.',
      'handler_file' => __DIR__ . '/operations/supplier_brand_dictionary.php',
      'handler_func' => 'op_supplier_brand_dictionary_only_for_supplier_products',
      'supplier_products_db_handler' => 'supplier_products_db_op_sync_wb_brands_category',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'marketplace_data',
      'params' => [
        'wb_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения WB',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'category_value' => [
          'type' => 'string',
          'title' => 'Subject ID WB',
          'default' => '',
          'required' => false,
          'max_len' => 191,
        ],
        'category_values_json' => [
          'type' => 'string',
          'title' => 'JSON списка выбранных категорий WB',
          'default' => '[]',
          'required' => false,
          'max_len' => 50000,
        ],
        'refresh_days' => [
          'type' => 'string',
          'title' => 'Считать справочник категории свежим N дней',
          'default' => '30',
          'required' => false,
          'max_len' => 5,
        ],
        'force_refresh' => [
          'type' => 'string',
          'title' => 'Принудительно обновить категорию',
          'default' => '1',
          'required' => false,
          'max_len' => 1,
        ],
      ],
    ],

    'run_pipeline' => [
      'title' => 'run_pipeline (последовательный запуск нескольких операций)',
      'description' => 'Запускает выбранные операции последовательно на выбранных товарах. Каждая следующая операция стартует с уже обновлённого датасета (inplace=1).',
      'handler_file' => __DIR__ . '/operations/run_pipeline.php',
      'handler_func' => 'op_run_pipeline',
      'redirect_to_report' => false,
      'params' => [
        'ops_json' => [
          'type' => 'string',
          'title' => 'JSON массива op_type (internal)',
          'default' => '[]',
          'required' => true,
          'max_len' => 20000,
        ],
        'model' => [
          'type' => 'string',
          'title' => 'LLM model (глобально, опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 80,
        ],
        'op_models_json' => [
          'type' => 'string',
          'title' => 'JSON карты op_type => LLM model (internal)',
          'default' => '{}',
          'required' => false,
          'max_len' => 20000,
        ],
        'op_image_models_json' => [
          'type' => 'string',
          'title' => 'JSON карты op_type => GPT Image model (internal)',
          'default' => '{}',
          'required' => false,
          'max_len' => 20000,
        ],
        'op_params_json' => [
          'type' => 'string',
          'title' => 'JSON карты op_type => параметры операции (internal)',
          'default' => '{}',
          'required' => false,
          'max_len' => 20000,
        ],
        'ozon_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Ozon (для DB-операций поставщика)',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'wb_connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения WB (для DB-операций поставщика)',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'max_items' => [
          'type' => 'string',
          'title' => 'max_items (глобально, опционально)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'brand_list' => [
          'type' => 'string',
          'title' => 'Список брендов поставщика для операции Бренд из названия',
          'default' => '',
          'required' => false,
          'max_len' => 20000,
        ],
        'force_inplace' => [
          'type' => 'string',
          'title' => 'Принудительно inplace=1 и auto_dataset=0 (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'ozon_sync_products' => [
      'title' => 'ozon_sync_products (обновить товары Ozon в БД)',
      'description' => 'Загружает список товаров из Ozon (/v3/product/list) и сохраняет offer_id/product_id/sku в feedtools_ozon_products. Затем деактивирует исчезнувшие.',
      'handler_file' => __DIR__ . '/operations/ozon_sync_products.php',
      'handler_func' => 'op_ozon_sync_products',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'marketplace_data',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'supplier_id' => [
          'type' => 'string',
          'title' => 'ID поставщика для обновления справочника брендов',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
      ],
    ],

    'ozon_sync_analytics' => [
      'title' => 'ozon_sync_analytics (аналитика товаров Ozon)',
      'description' => 'Загружает товарную аналитику Ozon за период до 90 дней: показы, корзину, конверсии, заказы, доставленные, возвраты, отмены и рекламные метрики. Сохраняет данные по дням и SKU.',
      'handler_file' => __DIR__ . '/operations/ozon_sync_analytics.php',
      'handler_func' => 'op_ozon_sync_analytics',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'marketplace_data',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => true,
          'max_len' => 20,
        ],
        'days' => [
          'type' => 'string',
          'title' => 'Период, дней (1-90)',
          'default' => '90',
          'required' => false,
          'max_len' => 3,
        ],
        'date_from' => [
          'type' => 'string',
          'title' => 'Дата начала YYYY-MM-DD (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 10,
        ],
        'date_to' => [
          'type' => 'string',
          'title' => 'Дата окончания YYYY-MM-DD (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 10,
        ],
        'metrics' => [
          'type' => 'string',
          'title' => 'Метрики через запятую (пусто = все известные)',
          'default' => '',
          'required' => false,
          'max_len' => 2000,
        ],
        'limit' => [
          'type' => 'string',
          'title' => 'Размер страницы Ozon API',
          'default' => '1000',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'wb_sync_analytics' => [
      'title' => 'wb_sync_analytics (аналитика товаров Wildberries)',
      'description' => 'Загружает дневную товарную аналитику Wildberries за период до 90 дней через отчет Product Cards Statistics per Days: переходы в карточку, корзину, заказы, выкупы, отмены, суммы и конверсии.',
      'handler_file' => __DIR__ . '/operations/wb_sync_analytics.php',
      'handler_func' => 'op_wb_sync_analytics',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'marketplace_data',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения Wildberries',
          'default' => '0',
          'required' => true,
          'max_len' => 20,
        ],
        'days' => [
          'type' => 'string',
          'title' => 'Период, дней (1-90)',
          'default' => '90',
          'required' => false,
          'max_len' => 3,
        ],
        'date_from' => [
          'type' => 'string',
          'title' => 'Дата начала YYYY-MM-DD (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 10,
        ],
        'date_to' => [
          'type' => 'string',
          'title' => 'Дата окончания YYYY-MM-DD (опционально)',
          'default' => '',
          'required' => false,
          'max_len' => 10,
        ],
        'timeout_sec' => [
          'type' => 'string',
          'title' => 'Сколько ждать готовности отчета, сек',
          'default' => '1200',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'ozon_sync_actions' => [
      'title' => 'ozon_sync_actions (обновить акции Ozon в БД)',
      'description' => 'Загружает список акций Ozon и товары, которые уже участвуют или могут участвовать в них. Сохраняет цены входа в акции и параметры эластичного бустинга в локальную БД.',
      'handler_file' => __DIR__ . '/operations/ozon_sync_actions.php',
      'handler_func' => 'op_ozon_sync_actions',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'price_tool',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'limit' => [
          'type' => 'string',
          'title' => 'Размер страницы Ozon API',
          'default' => '100',
          'required' => false,
          'max_len' => 5,
        ],
        'max_actions' => [
          'type' => 'string',
          'title' => 'Ограничить число акций (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 6,
        ],
        'sync_products' => [
          'type' => 'string',
          'title' => 'Синхронизировать уже участвующие товары (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'sync_candidates' => [
          'type' => 'string',
          'title' => 'Синхронизировать кандидатов на участие (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'ozon_push_selected_feeds' => [
      'title' => 'ozon_push_selected_feeds (выгрузить цены по выбранным фидам в Ozon)',
      'description' => 'Скачивает XML по выбранным профилям Ozon Price Tool, рассчитывает цены для всех товаров и отправляет в Ozon обычную цену, min price и изменения по акциям.',
      'handler_file' => __DIR__ . '/operations/ozon_push_selected_feeds.php',
      'handler_func' => 'op_ozon_push_selected_feeds',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'price_tool',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'feed_ids_json' => [
          'type' => 'string',
          'title' => 'JSON массива id фидов',
          'default' => '[]',
          'required' => true,
          'max_len' => 20000,
        ],
      ],
    ],

    'ozon_fbo_refresh' => [
      'title' => 'ozon_fbo_refresh (обновить FBO Tool)',
      'description' => 'Обновляет FBO-остатки, текущие цены, индекс цены и аналитику FBO-товаров Ozon в фоне.',
      'handler_file' => __DIR__ . '/operations/ozon_fbo_refresh.php',
      'handler_func' => 'op_ozon_fbo_refresh',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'ozon',
      'service_key' => 'fbo_tool',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => true,
          'max_len' => 20,
        ],
        'mode' => [
          'type' => 'string',
          'title' => 'Режим обновления',
          'default' => 'full',
          'required' => false,
          'max_len' => 20,
        ],
        'offer_ids_json' => [
          'type' => 'string',
          'title' => 'JSON массива offer_id',
          'default' => '[]',
          'required' => false,
          'max_len' => 20000,
        ],
      ],
    ],

    'wb_sync_promotions' => [
      'title' => 'wb_sync_promotions (обновить акции WB в БД)',
      'description' => 'Загружает календарь акций Wildberries, детали акций и товары-участники/кандидаты с текущими и плановыми скидками. Сохраняет данные для контроля слишком высоких скидок и расчёта цен под акции.',
      'handler_file' => __DIR__ . '/operations/wb_sync_promotions.php',
      'handler_func' => 'op_wb_sync_promotions',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'price_tool',
      'queue_lane' => 'wb_promotions',
      'dataset_lock' => false,
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'days_back' => [
          'type' => 'string',
          'title' => 'Сколько дней назад захватывать',
          'default' => '7',
          'required' => false,
          'max_len' => 5,
        ],
        'days_ahead' => [
          'type' => 'string',
          'title' => 'Сколько дней вперёд захватывать',
          'default' => '45',
          'required' => false,
          'max_len' => 5,
        ],
        'all_promo' => [
          'type' => 'string',
          'title' => 'Все акции, включая недоступные (1/0)',
          'default' => '0',
          'required' => false,
          'max_len' => 5,
        ],
        'limit' => [
          'type' => 'string',
          'title' => 'Размер страницы WB API',
          'default' => '1000',
          'required' => false,
          'max_len' => 5,
        ],
        'max_promotions' => [
          'type' => 'string',
          'title' => 'Ограничить число акций (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 6,
        ],
        'sync_products' => [
          'type' => 'string',
          'title' => 'Синхронизировать уже участвующие товары (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'sync_candidates' => [
          'type' => 'string',
          'title' => 'Синхронизировать кандидатов на участие (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'max_products_per_promotion' => [
          'type' => 'string',
          'title' => 'Ограничить товаров на акцию (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 8,
        ],
        'danger_plan_discount_percent' => [
          'type' => 'string',
          'title' => 'Скидка, которую считать рискованной',
          'default' => '60',
          'required' => false,
          'max_len' => 6,
        ],
      ],
    ],

    'wb_import_promotion_xlsx_folder' => [
      'title' => 'wb_import_promotion_xlsx_folder (импорт XLS/XLSX автоакций WB из папки)',
      'description' => 'Сканирует папку с XLS/XLSX-файлами автоакций Wildberries, разбирает новые файлы, сохраняет плановые цены/скидки и переносит обработанные файлы в архив.',
      'handler_file' => __DIR__ . '/operations/wb_import_promotion_xlsx_folder.php',
      'handler_func' => 'op_wb_import_promotion_xlsx_folder',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'price_tool',
      'queue_lane' => 'wb_promotions',
      'dataset_lock' => false,
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'inbox_dir' => [
          'type' => 'string',
          'title' => 'Папка с XLS/XLSX автоакций',
          'default' => '',
          'required' => false,
          'max_len' => 500,
        ],
        'max_files' => [
          'type' => 'string',
          'title' => 'Максимум файлов за запуск (0 = без лимита)',
          'default' => '0',
          'required' => false,
          'max_len' => 6,
        ],
        'min_age_sec' => [
          'type' => 'string',
          'title' => 'Не трогать файлы моложе N секунд',
          'default' => '10',
          'required' => false,
          'max_len' => 6,
        ],
        'move_processed' => [
          'type' => 'string',
          'title' => 'Переносить успешные файлы в _processed (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'move_failed' => [
          'type' => 'string',
          'title' => 'Переносить ошибочные файлы в _failed (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
      ],
    ],

    'wb_download_promotion_xlsx' => [
      'title' => 'wb_download_promotion_xlsx (скачать и импортировать XLS/XLSX автоакций WB)',
      'description' => 'По сохранённому cURL-шаблону кабинета WB скачивает XLS/XLSX активных автоакций, сохраняет сроки из календаря акций и импортирует плановые цены.',
      'handler_file' => __DIR__ . '/operations/wb_download_promotion_xlsx.php',
      'handler_func' => 'op_wb_download_promotion_xlsx',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'price_tool',
      'queue_lane' => 'wb_promotions',
      'dataset_lock' => false,
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'inbox_dir' => [
          'type' => 'string',
          'title' => 'Папка для скачанных XLS/XLSX',
          'default' => '',
          'required' => false,
          'max_len' => 1024,
        ],
        'days_ahead' => [
          'type' => 'string',
          'title' => 'Сколько дней вперёд брать акции',
          'default' => '45',
          'required' => false,
          'max_len' => 4,
        ],
        'max_promotions' => [
          'type' => 'string',
          'title' => 'Максимум акций за запуск',
          'default' => '20',
          'required' => false,
          'max_len' => 4,
        ],
        'only_auto' => [
          'type' => 'string',
          'title' => 'Только автоакции',
          'default' => '1',
          'required' => false,
          'max_len' => 1,
        ],
        'import_after_download' => [
          'type' => 'string',
          'title' => 'Импортировать после скачивания',
          'default' => '1',
          'required' => false,
          'max_len' => 1,
        ],
      ],
    ],

    'wb_push_selected_feeds' => [
      'title' => 'wb_push_selected_feeds (выгрузить цены по выбранным фидам в WB)',
      'description' => 'Скачивает XML по выбранным профилям WB Price Tool, рассчитывает цену, скидку продавца и скидку WB Клуба, затем отправляет изменения в Wildberries.',
      'handler_file' => __DIR__ . '/operations/wb_push_selected_feeds.php',
      'handler_func' => 'op_wb_push_selected_feeds',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'price_tool',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'feed_ids_json' => [
          'type' => 'string',
          'title' => 'JSON массива id фидов',
          'default' => '[]',
          'required' => true,
          'max_len' => 20000,
        ],
      ],
    ],

    'yandex_push_selected_feeds' => [
      'title' => 'yandex_push_selected_feeds (выгрузить цены по выбранным фидам в Яндекс Маркет)',
      'description' => 'Скачивает XML по выбранным профилям Яндекс Price Tool, получает цены, карточки, рекомендации и тарифы площадки, рассчитывает цену и отправляет изменения в Яндекс Маркет.',
      'handler_file' => __DIR__ . '/operations/yandex_push_selected_feeds.php',
      'handler_func' => 'op_yandex_push_selected_feeds',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'yandex_market',
      'service_key' => 'price_tool',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'feed_ids_json' => [
          'type' => 'string',
          'title' => 'JSON массива id фидов',
          'default' => '[]',
          'required' => true,
          'max_len' => 20000,
        ],
      ],
    ],

    'wb_sync_products' => [
      'title' => 'wb_sync_products (обновить товары WB в БД)',
      'description' => 'Загружает список карточек Wildberries (/content/v2/get/cards/list) и сохраняет vendorCode/nmID/imtID/subjectID в feedtools_wb_products. Фильтр "Только отсутствующие на WB" читает эту таблицу без обращения к API.',
      'handler_file' => __DIR__ . '/operations/wb_sync_products.php',
      'handler_func' => 'op_wb_sync_products',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'wb',
      'service_key' => 'marketplace_data',
      'params' => [
        'connection_id' => [
          'type' => 'string',
          'title' => 'ID подключения маркетплейса',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
        'supplier_id' => [
          'type' => 'string',
          'title' => 'ID поставщика для обновления справочника брендов',
          'default' => '0',
          'required' => false,
          'max_len' => 20,
        ],
      ],
    ],

    'master_mobile_feed' => [
      'title' => 'master_mobile_feed (Master Mobile: парсинг и сборка фида)',
      'description' => 'Запускает парсинг остатков Master Mobile, сборку полного XML-фида, подмешивание чистых фото и закупочных цен.',
      'handler_file' => __DIR__ . '/operations/master_mobile_feed.php',
      'handler_func' => 'op_master_mobile_feed',
      'redirect_to_report' => false,
      'global_op' => true,
      'marketplace' => 'supplier_feed',
      'service_key' => 'supplier_feed',
      'params' => [
        'task_key' => [
          'type' => 'string',
          'title' => 'Задача',
          'default' => 'parse_and_build',
          'required' => false,
          'max_len' => 64,
        ],
        'price_mode' => [
          'type' => 'string',
          'title' => 'Источник цен',
          'default' => 'pricelist',
          'required' => false,
          'max_len' => 32,
        ],
        'workers' => [
          'type' => 'string',
          'title' => 'Потоков парсинга',
          'default' => '12',
          'required' => false,
          'max_len' => 3,
        ],
        'upload_feed' => [
          'type' => 'string',
          'title' => 'Загружать фид на FTP (1/0)',
          'default' => '1',
          'required' => false,
          'max_len' => 5,
        ],
        'limit' => [
          'type' => 'string',
          'title' => 'Лимит товаров для теста (0 = все)',
          'default' => '0',
          'required' => false,
          'max_len' => 10,
        ],
        'snapshot_path' => [
          'type' => 'string',
          'title' => 'Путь snapshot остатков',
          'default' => 'storage/master_mobile/price_stock_snapshot.yml',
          'required' => false,
          'max_len' => 255,
        ],
        'feed_path' => [
          'type' => 'string',
          'title' => 'Путь итогового XML',
          'default' => 'storage/master_mobile/master_mobile_info.xml',
          'required' => false,
          'max_len' => 255,
        ],
        'image_replacements_path' => [
          'type' => 'string',
          'title' => 'CSV чистых фото',
          'default' => 'storage/master_mobile/clean_images/feed_picture_replacements_new_articles.csv',
          'required' => false,
          'max_len' => 255,
        ],
        'purchase_prices_path' => [
          'type' => 'string',
          'title' => 'Прайс закупочных цен',
          'default' => 'storage/master_mobile/pricelists/master_mobile_prices_current.xlsx',
          'required' => false,
          'max_len' => 255,
        ],
      ],
    ],


  ];
}
